title: P2PU & BLCS
description: "Os Círculos de Aprendizagem estão a chegar a Braga! \nJunte-se a nós\
  \ na biblioteca para aprendermos algo juntos. Os círculos de aprendizagem reúnem\
  \ semanalmente de 6 a 8 semanas. A participação é gratuita."
language: pt
